export const DEPARTMENTS = [
  "Accounting",
  "Adult Education",
  "Agricultural Science & Education",
  "Agriculture",
  "Arabic & Literary Studies",
  "Arabic Studies",
  "Banking & Finance",
  "Biochemistry",
  "Biology",
  "Botany",
  "Business Administration",
  "Chemistry",
  "Civil Engineering",
  "Common & Islamic Law",
  "Computer Science",
  "Computer Science Education",
  "Criminology & Security Studies",
  "Curriculum Studies",
  "Cyber Security",
  "Demography & Social Statistics",
  "Dentistry",
  "Optometry",
  "Pharmacy",
  "Physiotherapy",
  "Economics",
  "Education & Arabic",
  "Education & Biology",
  "Education & Chemistry",
  "Education & Economics",
  "Education & English Language",
  "Education & French",
  "Education & Geography",
  "Education & Hausa",
  "Education & History",
  "Education & Islamic Studies",
  "Education & Mathematics",
  "Education & Physics",
  "Educational Management",
  "Electrical / Electronics Engineering",
  "Employment Relations & Human Resource Management",
  "English Language",
  "Entrepreneurship & Innovation",
  "Environmental Resources Management",
  "Fisheries",
  "Forestry / Forest Resources Management",
  "French",
  "Geography",
  "Geology",
  "Guidance & Counselling",
  "Hadith Studies",
  "Hausa",
  "History & International Relations",
  "Industrial Chemistry",
  "Information & Communication Engineering",
  "Islamic Studies",
  "Library & Information Science",
  "Linguistics",
  "Literature In English",
  "Local Government And Development Studies",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Medicine & Surgery",
  "Microbiology",
  "Nursing / Nursing Science",
  "Nutrition & Dietetics",
  "Physics",
  "Political Science",
  "Pre-Primary & Primary Education",
  "Public Administration",
  "Quranic Studies",
  "Radiography",
  "Shariah",
  "Social Studies",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Taxation",
  "Veterinary Medicine",
  "Zoology",
] as const;

export type Department = (typeof DEPARTMENTS)[number];